language: python
python:
    - "2.7"
services:
  - postgresql
postgres:
  adapter: postgresql
  database: discover_flask_dev_db
  username: postgres
before_script:
  - psql -c 'create database discover_flask_dev_db;' -U postgres
addons:
  postgresql: "9.6"
cache: pip
install: pip install -r requirements.txt
env:
  global:
    - TRAVIS_BUILD=true
branches:
  only:
      - master
script:
  - python test.py
notifications:
  email:
    on_success: never
    on_failure: never
